name: square_depth_seg

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim, depth, segmentation
  obs:
    agentview_depth:
      shape: [1, 90, 160]
      type: depth
    # robot0_eye_in_hand_depth:
    #   shape: [1, 90, 160]
    #   type: depth
    agentview_segmentation_instance:
      shape: [1, 90, 160]  # CxHxW; C is binary
      type: segmentation
    robot0_eye_in_hand_segmentation_instance:
      shape: [1, 90, 160]
      type: segmentation
    robot0_eef_pos:
      shape: [3]
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [10]

task_name: &task_name square
dataset_type: &dataset_type ph

dataset_path: &dataset_path datasets/generated/NutAssemblySquare/2024-11-11-merged-cpgen-naive-env-reset/agentview_depth.hdf5
abs_action: &abs_action True

env_runner:
  _target_: adaflow.env_runner.robomimic_image_runner.RobomimicImageRunner
  dataset_path: *dataset_path
  shape_meta: *shape_meta
  # costs 1GB per env
  n_train: 8
  n_train_vis: 8
  train_start_idx: 0
  n_test: 50
  n_test_vis: 50
  test_start_seed: 100000
  # use python's eval function as resolver, single-quoted string as argument
  max_steps: ${eval:'400 if "${task.dataset_type}" == "mh" else 400'}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_obs_key: 'agentview_depth'
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  tqdm_interval_sec: 1.0
  n_envs: 15
  camera_depths: True
  camera_segmentations: instance
# evaluation at this config requires a 16 core 64GB instance.

dataset:
  _target_: adaflow.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02
  norm_args:
    robot0_eye_in_hand_depth:
      clamp_max: 0.5
    agentview_depth:
      clamp_max: 1.4
  use_depth_aug: True
  depth_handler_cfg: 
    depth_handler:
      augmentation:
        depth_warping:
          enabled: True
          prob: 0.8
          std: 0.75
        gaussian_blur:
          enabled: True
          kernel_size: 5
          sigma_lower: 0.01
          sigma_upper: 1.0
        scale:
          enabled: True
          intensity: 0.05
          prob: 0.4
        holes:
          enabled: True
          prob: 0.5
          kernel_size_lower: 3
          kernel_size_upper: 27
          sigma_lower: 1.0
          sigma_upper: 7.0
          thresh_lower: 0.6
          thresh_upper: 0.9
          fill_value: 1.0