defaults:
  - _self_
  - task: square_depth_seg_abs

name: train_diffusion_unet_image
_target_: adaflow.workspace.train_diffusion_unet_image_workspace.TrainDiffusionUnetImageWorkspace

task_name: ${task.name}
dataset_type: ${task.dataset_type}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 1
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
normalize_pixel: False

policy:
  _target_: adaflow.policy.diffusion_unet_image_policy.DiffusionUnetImagePolicy

  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    # beta_schedule is important
    # this is the best we found
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small # Yilun's paper uses fixed_small_log instead, but easy to cause Nan
    clip_sample: True # required when predict_epsilon=False
    # set_alpha_to_one: True
    # steps_offset: 0
    prediction_type: epsilon # or sample

  obs_encoder:
    _target_: adaflow.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    rgb_model:
      _target_: adaflow.model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    # crop_shape: [76, 76]
    # SquareReal
    crop_shape: [84, 84]
    # constant center crop
    random_crop: True
    fixed_crop: True
    fixed_crop_shape:
      robot0_eye_in_hand_segmentation_instance: [90, 160]
      agentview_segmentation_instance: [90, 90]
    resize_shape: null
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True
    depth_norm: False
    use_rgb_input: False
    use_depth_input: False  # use segmentation as policy input or not
    use_segmentation_input: True  # use segmentation as policy input or not
    # keys_to_use: ["agentview_segmented_depth", "robot0_eye_in_hand_segmentation_instance"]
    norm_args:
      # nut-assembly-square
      # robot0_eye_in_hand_depth:
      #   clamp_max: 1.00
      #   mean: 0.018 #0.177
      #   std: 0.133 #0.1699
      # agentview_depth:
      #   clamp_max: 1.75
      #   mean: 0.499 #0.778
      #   std: 0.499 #0.349
      # NutAssemblySquareCompositeRobotDeoxysStart
      # robot0_eye_in_hand_depth:
      #   clamp_max: 1.00
      #   mean: 0.018 #0.177
      #   std: 0.133 #0.1699
      # agentview_depth:
      #   clamp_max: 1.75
      #   mean: 0.499 #0.778
      #   std: 0.499 #0.349
      # square-d1
      # robot0_eye_in_hand_depth:
      #     clamp_max: 1
      #     mean: 0.011
      #     std: 0.105
      # agentview_depth:
      #     clamp_max: 1.75
      #     mean: 0.513
      #     std: 0.499
      # NutAssemblySquareCompositeRobotReal
      # robot0_eye_in_hand_depth:
      #   clamp_max: 0.4
      #   mean: 0.20
      #   std: 0.05
      # agentview_depth:
      #   clamp_max: 1.4
      #   mean: 0.81
      #   std: 0.30
      # NutAssemblySquareCompositeRobotRealDeoxysStartBetter3PVCamera
      robot0_eye_in_hand_depth:
        clamp_max: 0.5
        mean: 0.21812304854393005
        std: 0.06115631386637688
      agentview_depth:
        clamp_max: 1.4
        mean: 0.8462300896644592
        std: 0.22116202116012573

  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100
  obs_as_global_cond: ${obs_as_global_cond}
  diffusion_step_embed_dim: 128
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True

ema:
  _target_: adaflow.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 64
  num_workers: 12
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  resume_dir: null
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 200
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  freeze_encoder: False
  # training loop control
  # in epochs
  rollout_every: 20
  checkpoint_every: 20
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  pretrained_ckpt: null

logging:
  project: adaflow
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: exps/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_${dataset_type}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}_${dataset_type}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: exps/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_${dataset_type}
  sweep:
    dir: exps/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_${dataset_type}
    subdir: ${hydra.job.num}
