defaults:
  - _self_
  - task: libero_image_abs

name: train_adaflow_unet_image
_target_: adaflow.workspace.train_adaflow_unet_image_workspace.TrainAdaflowUnetImageWorkspace

task_name: ${task.name}
dataset_type: ${task.dataset_type}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True

policy:
  _target_: adaflow.policy.adaflow_unet_image_policy.AdaflowUnetImagePolicy

  shape_meta: ${shape_meta}

  obs_encoder:
    _target_: adaflow.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    rgb_model:
      _target_: adaflow.model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    resize_shape: null
    crop_shape: [76, 76]
    # constant center crop
    random_crop: True
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True

  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 20
  obs_as_global_cond: ${obs_as_global_cond}
  diffusion_step_embed_dim: 128
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True
  pos_emb_scale: 100

  pretrained_rf_ckpt: ""

ema:
  _target_: adaflow.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  resume_dir: null
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 8000
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  freeze_encoder: False
  # training loop control
  # in epochs
  rollout_every: 50
  checkpoint_every: 50
  val_every: 1
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  pretrained_ckpt: null

logging:
  project: adaflow
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: exps/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_${dataset_type}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}_${dataset_type}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: exps/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_${dataset_type}
  sweep:
    dir: exps/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_${dataset_type}
    subdir: ${hydra.job.num}
